### ISSUE TITLE
Doesn't work with coupon codes and causes 503

### ISSUE THREAD

**Issue by hitinder** [razorpay/razorpay-prestashop#33]
After I installed it on the Prestashop and tried to add a coupon code at the first checkout step, it caused the website to stop and I ended up getting 503.

Error 503 is only on that particular browser.

Steps to reproduce:
1. Install the plugin
2. Enabled authorize and capture
3. Add item to cart
4. Apply a promo code
5. The website will just stop and do nothing and finally end up giving 503

Solution: Clear the cache and delete all browser data and the site will start working.

Version: 2.2.0
Prestashop: 1.7.5.1

**Comment by ramth05** [comment]
@hitinder , We just released new version 2.3.0 with the fix for issue listed above. Can you please verify it once in your test site, and please let us know if still some issue.

**Comment by hitinder** [comment]
@ramth05 
If I install the plugin on a subdomain, e.g. test.mywebsite.com. Will your plugin work with the live parameters (keys) without any problem?

**Comment by ramth05** [comment]
> @ramth05
> If I install the plugin on a subdomain, e.g. test.mywebsite.com. Will your plugin work with the live parameters (keys) without any problem?

@hitinder plugin doesn't depend on domain it's only depend on key:secret . So hopefully it should work without any issue.

**Comment by hitinder** [comment]
@ramth05 it's not working. After applying ore removing the coupon code the payment popup still shows up with the old order value.

![image](https://user-images.githubusercontent.com/9841229/70210230-3a80f900-1743-11ea-893b-c727e97f5d4d.png)

![image](https://user-images.githubusercontent.com/9841229/70210592-1a056e80-1744-11ea-857e-1ee506befc27.png)

**Comment by ramth05** [comment]
> @ramth05 it's not working. After applying ore removing the coupon code the payment popup still shows up with the old order value.
> 
> Check the popup amount and the amount behind the overlay window.
> 
> ![image](https://user-images.githubusercontent.com/9841229/70210800-add73a80-1744-11ea-9b69-b768876a4ccf.png)
> 
> ![image](https://user-images.githubusercontent.com/9841229/70210838-bdef1a00-1744-11ea-838d-fb01ec10d3cb.png)

@hitinder Can you please pass us details of your test or clone site. We need to look issue in your site as unable to replicate it at our end. Before sending us details can you please just remove full installation 'razorpay' folder from modules and clear the cache etc and try to install it again and test it. If it's not working please provide us clone site details to look more into it.

**Comment by hitinder** [comment]
@ramth05 Working like a charm. It was the cache indeed.

Should I be worried about the below calls taking so much time?

![image](https://user-images.githubusercontent.com/9841229/70214267-360d0e00-174c-11ea-82bb-40368c3b9b4e.png)

**Comment by ramth05** [comment]
> @ramth05 Working like a charm. It was the cache indeed.
> 
> Should I be worried about the below calls taking so much time?
> 
> ![image](https://user-images.githubusercontent.com/9841229/70214267-360d0e00-174c-11ea-82bb-40368c3b9b4e.png)

@hitinder Thanks for testing it confirming us. I don't think it's related with plugin code. it's must be some time network issue. Please test it throughly before deploying it production. Thanks again for help in testing.

**Comment by umanghome** [comment]
You don't have to worry about these requests taking time. They are async and non-blocking. Only if one of Razorpay's JS or CSS files were taking time, it would be something to be concerned about.

Thanks for pointing the high response times out - we've raised them to the team.

**Comment by hitinder** [comment]
@umanghome @ramth05 I flagged them because I believe content like **aritel.svg** should be marked as static and need not to be loaded for each call. At present this particular SVG file is loading on each call.

**Comment by hitinder** [comment]
Another thing I noticed is that in the BO it doesn't show RazorPay logo anymore but shows a question mark logo.

![image](https://user-images.githubusercontent.com/9841229/70215666-0b708480-174f-11ea-8ed5-33a99db4d4ff.png)

**Comment by ramth05** [comment]
> Another thing I noticed is that in the BO it doesn't show RazorPay logo anymore but shows a question mark logo.
> 
> ![image](https://user-images.githubusercontent.com/9841229/70215666-0b708480-174f-11ea-8ed5-33a99db4d4ff.png)

@hitinder thanks for pointing it, we will check and update it soon.

**Comment by ramth05** [comment]
> > Another thing I noticed is that in the BO it doesn't show RazorPay logo anymore but shows a question mark logo.
> > ![image](https://user-images.githubusercontent.com/9841229/70215666-0b708480-174f-11ea-8ed5-33a99db4d4ff.png)
> 
> @hitinder thanks for pointing it, we will check and update it soon.

@hitinder just updated the logo in same release `razorpay.zip` file.  We will update new release with this fix soon.

**Comment by ramth05** [comment]
Already supported in latest release.
